#!/usr/bin/env bash

build () {
    rm -rf wasm-module
    mkdir wasm-module
    cargo build --target wasm32-unknown-unknown
    wasm-bindgen ../target/wasm32-unknown-unknown/debug/cicada_wasm.wasm --out-dir wasm-module
}

release () {
    rm -rf wasm-module
    mkdir wasm-module
    cargo build --release --target wasm32-unknown-unknown
    wasm-bindgen ../target/wasm32-unknown-unknown/release/cicada_wasm.wasm --out-dir wasm-module
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
