#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const cicada = require("./cicada-script.js");

function main ()
{
    let arg_vect = process.argv.slice(2);
    let script =
        fs.readFileSync ("./core-script.cs")
        .toString ();
    for (let arg of arg_vect) {
        let arg_script =
            fs.readFileSync (arg)
            .toString ();
        script = script.concat (arg_script);
    }
    let env = cicada.eval_script (script);
    console.log (env.data_stack);
}

main ();
