#!/usr/bin/env node

const fs = require ("fs");
const cicada = require ("./cicada-script.js");

function repl ()
{
    eval_file_vect ([]);
    return;
}

function eval_file_vect (file_vect)
{
    let script =
        fs.readFileSync ("./core-script.cs")
        .toString ();
    for (let file of file_vect) {
        let file_script =
            fs.readFileSync (file)
            .toString ();
        script = script.concat (file_script);
    }
    let env = cicada.eval_script (script);
    console.log (env.data_stack);
}

function main ()
{
    let arg_vect = process.argv.slice (2);
    if (arg_vect.length === 0)
        repl ();
    else
        eval_file_vect (arg_vect);
}

main ();
