#!/usr/bin/env bash

build () {
    cargo build --target wasm32-unknown-unknown
    wasm-bindgen ../../target/wasm32-unknown-unknown/debug/cicada_notebook.wasm --out-dir wasm_modules
}

release () {
    cargo build --release --target wasm32-unknown-unknown
    wasm-bindgen ../../target/wasm32-unknown-unknown/release/cicada_notebook.wasm --out-dir wasm_modules
}

update () {
    cargo update
    npm install
}

dist () {
    rm dist/*
    cp node_modules/react/umd/react.development.js dist
    cp node_modules/react-dom/umd/react-dom.development.js dist
    npx webpack
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
