#!/usr/bin/env bash

build () {
    cargo build --target wasm32-unknown-unknown
    wasm-bindgen ../../target/wasm32-unknown-unknown/debug/cicada_notebook.wasm --out-dir wasm_modules
}

release () {
    cargo build --release --target wasm32-unknown-unknown
    wasm-bindgen ../../target/wasm32-unknown-unknown/release/cicada_notebook.wasm --out-dir wasm_modules
}

update () {
    cargo update
    npm install
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
