#! /bin/bash

IPKG=cicada.ipkg

build ()
{
    time idris --build $IPKG
}

clean ()
{
    idris --clean $IPKG
}

test () {
    idris --testpkg $IPKG
}

default () {
    build
}

if [ $# -eq 0 ]; then
    default
else
    $1
fi
